Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,44 +2,48 @@ name: Build APK
 
 # Controls when the action will run.
 on:
-  # Triggers the workflow on push or pull request events but only for the main and experimental branches
   push:
     branches: [ main, experimental ]
   pull_request:
     branches: [ main, experimental ]
-
-  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   buildAndroid:
-    # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
 
       - uses: krdlab/setup-haxe@master
         with:
           haxe-version: 4.2.5
-      # Runs a set of commands using the runner's shell
-      - name: Install Haxelib
+
+      # Installing required dependencies for Haxe and Android
+      - name: Install Dependencies
         run: |
-          sudo apt-get install libvlc-dev
-          sudo apt-get install libvlccore-dev
+          sudo apt-get update
+          sudo apt-get install -y libvlc-dev libvlccore-dev openjdk-11-jdk android-sdk
+
+      # Install Haxelib and other Haxe libraries
+      - name: Install Haxelib and Haxe Dependencies
+        run: |
           haxelib setup ~/haxelib
-          haxelib install hxcpp > /dev/null --quiet
-          haxelib install hmm --quiet
-          haxelib run hmm install
+          haxelib install hxcpp --quiet || echo "Failed to install hxcpp"
+          haxelib install lime --quiet || echo "Failed to install lime"
+          haxelib install openfl --quiet || echo "Failed to install openfl"
+          haxelib install hmm --quiet || echo "Failed to install hmm"
+          haxelib run hmm install || echo "Failed to run hmm install"
+
       - name: Create Version Tag
         run: echo "${{github.run_id}}" > VERSION
+
       - name: Compile APK
         run: haxelib run lime build android --app-version="4.0.0-${{ github.run_id}}"
+
       - name: Publish APK Artifact
         uses: actions/upload-artifact@v3
         with:
           name: androidBuild
           path: 'export/release/android/bin'
+          retention-days: 1
